project:
  version: ${VERSION:local}

server:
  port: ${PORT:8080}

logging:
  file: 
    name: ${LOG_PATH:/tmp/java.log}
  level:
    org:
      springframework: ${LOG_LEVEL:INFO}

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:sqlite.db
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.SQLiteDialect
    show-sql: false
    hibernate.ddl-auto: create-drop 