project:
  version: ${VERSION:local}

server:
  port: ${PORT:8080}

logging:
  file: 
    name: ${LOG_PATH:/tmp/java.log}
  level:
    org:
      springframework: ${LOG_LEVEL:INFO}

spring:
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password: sa
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update
  h2:
    console:
      path: /h2