project:
  version: ${VERSION:local}

server:
  port: ${PORT:8080}

logging:
  file: 
    name: ${LOG_PATH:/tmp/java.log}
  level:
    org:
      springframework: ${LOG_LEVEL:INFO}

spring:
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    open-in-view: false
    properties:
      jakarta:
        persistence: 
          sharedCache: 
            mode: NONE
  h2:
    console:
      path: /h2